apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: secure-app-base
  annotations:
    security.policy/reviewed-by: "security-team"
    security.policy/review-date: "2025-01-01"

# Base resources
resources:
  - deployment.yaml

# Common labels applied to all resources
commonLabels:
  app.kubernetes.io/name: secure-app
  app.kubernetes.io/part-of: devsecops-pipeline
  app.kubernetes.io/managed-by: kustomize

# Common annotations
commonAnnotations:
  security.policy/scanned: "true"
  compliance.framework/cis-k8s: "validated"
  compliance.framework/nist: "validated"
  compliance.framework/soc2: "validated"

# Namespace configuration
namespace: devsecops-pipeline

# Name prefix for resources
namePrefix: secure-

# Image transformations
images:
  - name: your-registry.com/secure-app
    newTag: v1.0.0

# ConfigMap generator
configMapGenerator:
  - name: app-environment-config
    literals:
      - ENV=production
      - LOG_LEVEL=INFO
      - METRICS_ENABLED=true
    options:
      disableNameSuffixHash: true
      labels:
        app: secure-app
        component: config
        environment: production

# Secret generator (for demo purposes - use external secret management in production)
secretGenerator:
  - name: app-database-credentials
    literals:
      - username=app_user
      - password=secure_password_123
    type: Opaque
    options:
      disableNameSuffixHash: true
      labels:
        app: secure-app
        component: secrets
        environment: production

# Resource patches
patches:
  # Add security context to all containers
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/securityContext
        value:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 3000
          fsGroup: 2000
          seccompProfile:
            type: RuntimeDefault

# Replicas for base deployment
replicas:
  - name: secure-app
    count: 3

# Strategic merge patches
patchesStrategicMerge:
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: secure-app
    spec:
      template:
        metadata:
          annotations:
            security.scan/trivy: "passed"
            security.scan/snyk: "passed"
            security.scan/checkmarx: "passed"
            policy.validation/conftest: "passed"