apiVersion: v2
name: secure-app
description: A Helm chart for secure DevSecOps application with comprehensive security features
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - devsecops
  - security
  - kubernetes
  - microservices
home: https://github.com/your-org/secure-devsecops-pipeline
sources:
  - https://github.com/your-org/secure-devsecops-pipeline
maintainers:
  - name: DevSecOps Team
    email: devsecops@example.com
icon: https://example.com/icon.png
annotations:
  category: Security
  licenses: Apache-2.0
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "23.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled